server:
  port: 9999
  tomcat:
    uri-encoding: UTF-8
spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: url
    password: password
    username: username

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    removeAbandoned: true
    removeAbandonedTimeout: 180
    filters: stat,wall
    logSlowSql: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  data:
    elasticsearch:
      repositories:
        enabled: false

  redis:
    database: 0
    host: host
    port: 1111
    password: password
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1201000ms
        min-idle: 0
    timeout: 30000ms


readm:
  data:
    es:
      username: username
      passwd: passwd
      host: host
      port: 9200
      number_of_shards: 3
      number_of_replicas: 3